// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"github.com/uilki/lgc/api/server"
)

// Injectors from wire.go:

func InitializeServer(pass string) (*server.Server, error) {
	backlogger, err := server.NewBackLogger(pass)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(backlogger)
	return serverServer, nil
}
